[package]
name = "rosetta"
version = "0.1.0"
authors = ["Matthew Blode <m@blode.co>"]
edition = "2018"
readme = "README.md"
description = "A fast static site generator."
homepage = "https://github.com/mblode/rosetta"
repository = "https://github.com/mblode/rosetta"
license = "MIT"
keywords = ["static", "site", "generator", "blog"]


[dependencies]
pulldown-cmark = "0.5.0"
clap = {version = "2.33", features = ["yaml"]}
actix-web = "0.7.19"
chrono = "0.4.6"
failure = "0.1.5"
exitfailure = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
